apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-redirects-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-legacy-redirects-ip
    ingress.gcp.kubernetes.io/pre-shared-cert: exac-cert
    networking.gke.io/v1beta1.FrontendConfig: legacy-redirects-frontend-config
spec:
  rules:
  - host: exac.broadinstitute.org
