---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod
nameSuffix: '-blue'
labels:
  - pairs:
      deployment: blue
    includeSelectors: true
    includeTemplates: true
images:
  - name: gnomad-api
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-api
    newTag: 884479b
  - name: gnomad-browser
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-browser
    newTag: 884479b
patches:
- target:
    kind: Ingress
    name: gnomad-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: blue.gnomad.the-tgg.dev
- target:
    kind: Ingress
    name: gnomad-ingress
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        networking.gke.io/managed-certificates: env-managed-cert-blue
        networking.gke.io/v1beta1.FrontendConfig: gnomad-frontend-config-blue
- target:
    kind: ManagedCertificate
    name: env-managed-cert
  patch: |-
    - op: replace
      path: /spec/domains/0
      value: blue.gnomad.the-tgg.dev
# This replacement must be done in this kustomization, to ensure that the name nameSuffix is applied to the API_URL
replacements:
  - source:
      fieldPath: metadata.name
      kind: Service
      name: gnomad-api
      version: v1
    targets:
      - fieldPaths:
          - spec.template.spec.containers.0.env.0.value
        options:
          delimiter: /
          index: 2
        select:
          group: apps
          kind: Deployment
          name: gnomad-browser
          version: v1
