---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/gnomad-browser//deploy/manifests/browser/base?timeout=120&ref=a74e10c606912738f14fe7ffca8ec05d9f9c732d
labels:
  - pairs:
      deployment: blue
      tier: production
    includeSelectors: true
    includeTemplates: true
nameSuffix: -blue
images:
  - name: gcr.io/exac-gnomad/gnomad-api
    newTag: '5fe6dfed'
  - name: gcr.io/exac-gnomad/gnomad-browser
    newTag: '5fe6dfed'
replacements:
  - source:
      fieldPath: metadata.name
      kind: Service
      name: gnomad-api
      version: v1
    targets:
      - fieldPaths:
          - spec.template.spec.containers.[name=web].env.[name=API_URL].value
        options:
          delimiter: /
          index: 2
        select:
          group: apps
          kind: Deployment
          name: gnomad-browser
          version: v1
