---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-sumstats
  labels:
    service: gnomad-sumstats
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-sumstats
  template:
    metadata:
      labels:
        name: gnomad-sumstats
    spec:
      containers:
        - name: shiny
          image: gnomad-sumstats
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 800m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
