apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: legacy-redirects-settings
    literals:
    - ip=127.0.0.1
resources:
- legacy-redirects.deployment.yaml
- legacy-redirects.ingress.yaml
- legacy-redirects.service.yaml
