---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
labels:
  - pairs:
      environment: prod
    includeSelectors: true
    includeTemplates: true
replicas:
  - name: gnomad-api
    count: 2
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gnomad-api
      spec:
        template:
          spec:
            containers:
              - name: app
                resources:
                  requests:
                    cpu: '1'
                    memory: '11Gi'
                  limits:
                    cpu: '2'
                    memory: '12Gi'
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gnomad-api
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: NODE_OPTIONS
                    value: '--max-old-space-size=10240'
                  - name: JSON_CACHE_PATH
                    value: 'gs://gnomad-v4-gene-cache/2023-12-01'
                  - name: JSON_CACHE_LARGE_GENES
                    value: 'true'
                  - name: JSON_CACHE_COMPRESSION
                    value: 'true'
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all-deployments
      spec:
        template:
          spec:
            nodeSelector:
              cloud.google.com/gke-nodepool: 'main-pool'
    target:
      labelSelector: 'app=gnomad-browser'
