---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/gnomad-browser//deploy/manifests/blog/base?timeout=120&ref=141ca3938078db0ef56e0803082f0b55ce907839
images:
  - name: gnomad-blog
    newName: gcr.io/exac-gnomad/gnomad-blog
    newTag: '761cfac4'
  - name: gnomad-blog-auth
    newName: gcr.io/exac-gnomad/gnomad-blog-auth
    newTag: '761cfac4'
