---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: gnomad-blog
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-blog
    newTag: 'eb9fdade'
  - name: gnomad-blog-auth
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-blog-auth
    newTag: 'eb9fdade'
