apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
namePrefix: gp2-demo-
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: qa
      name: gp2-demo-exome-results-browsers
images:
  - name: exome-results-browsers
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/exome-results-browsers
    newTag: 91b1b25-gp2-demo-2026-06-24--21-32
patches:
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: exome-results-browsers
      spec:
        template:
          spec:
            volumes:
              - name: data
                gcePersistentDisk:
                  pdName: erb-data-gp2-demo-2026-06-17--19-12
