apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
namePrefix: demo2-
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: qa
      name: demo2-exome-results-browsers
images:
  - name: exome-results-browsers
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/exome-results-browsers
    newTag: f0e2135_2025-09-12_gp2-demo_1
patches:
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: exome-results-browsers
      spec:
        template:
          spec:
            volumes:
              - name: data
                gcePersistentDisk:
                  pdName: exome-results-browsers-data-2025-09-11--20-26
