---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/gnomad-browser//deploy/manifests/redis?timeout=120&ref=141ca3938078db0ef56e0803082f0b55ce907839
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: redis
      spec:
        template:
          spec:
            containers:
              - name: redis-server
                resources:
                  requests:
                    memory: 8Gi
                  limits:
                    memory: 8Gi
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: redis
      spec:
        volumeClaimTemplates:
          - metadata:
              name: redis-data
            spec:
              resources:
                requests:
                  storage: 30Gi

