---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-index
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>Hello from backend api!</h1>
      </body>
    </html>

