apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnomad-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnomad-api
  template:
    metadata:
      labels:
        app: gnomad-api
    spec:
      containers:
        - name: api
          image: gnomad-api
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: custom-index
