apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnomad-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnomad-browser
  template:
    metadata:
      labels:
        app: gnomad-browser
    spec:
      containers:
        - name: browser
          image: gnomad-browser-nginx
          env:
            - name: API_URL
              value: 'gnomad-api' # The service URL you want to proxy to
          volumeMounts:
            - name: browser-config-template
              mountPath: /etc/nginx/nginx.conf.template
              subPath: nginx.conf.template
          command: ['/bin/sh', '-c']
          args:
            - |
              envsubst "\$API_URL" < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
      volumes:
        - name: browser-config-template
          configMap:
            name: browser-config-template
