apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blog-sso-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: blog-sso-oauth-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gke-blog-sso-oauth
