---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
labels:
  - pairs:
      deployment: blue
    includeSelectors: true
    includeTemplates: true
nameSuffix: -blue
images:
  - name: gnomad-reads-server
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-reads-server
    newTag: 'ab4ac608'
  - name: gnomad-reads-api
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/gnomad-reads-api
    newTag: 'ab4ac608'
