---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/exome-results-browsers//deployment/manifests/?timeout=120&ref=030c679fe1716c1100207b6159623c4811cd52ba
namePrefix: demo-
labels:
  - pairs:
      deployment: 'demo'
    includeSelectors: true
    includeTemplates: true
images:
  - name: gcr.io/exac-gnomad/exome-results-browsers
    newName: gcr.io/gnomadev/exome-results-browsers
    newTag: '33aae1b'
patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: exome-results-browsers-ingress
        annotations:
          kubernetes.io/ingress.global-static-ip-name: demo-exome-results-browsers-ip
  - patch: |-
      - op: replace
        path: /spec/rules
        value:
          - host: mydemo.broadinstitute.org
            http:
              paths:
                - backend:
                    service:
                      name: exome-results-browsers
                      port:
                        number: 80
                  pathType: ImplementationSpecific
    target:
      kind: Ingress
      name: exome-results-browsers-ingress
