apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/exome-results-browsers//deployment/manifests/?timeout=120&ref=e597dd52cee6f3a393e4527b17dcdc99021f50bb
  - ingress.yaml
namePrefix: demo-
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: qa
      name: demo-exome-results-browsers
images:
  - name: gcr.io/exac-gnomad/exome-results-browsers
    newTag: a017321-rg_add_demo_kubernetes_yaml
patches:
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: exome-results-browsers
      spec:
        template:
          spec:
            volumes:
              - name: data
                gcePersistentDisk:
                  pdName: exome-results-browsers-data-240207-1325
