---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/broadinstitute/gnomad-browser//deploy/manifests/redis?timeout=120&ref=141ca3938078db0ef56e0803082f0b55ce907839
