---
apiVersion: v1
kind: Service
metadata:
  name: gnomad-api
  labels:
    app: gnomad-browser
    component: api
spec:
  type: NodePort
  selector:
    app: gnomad-browser
    component: api
    name: gnomad-api
  ports:
    - port: 80
      targetPort: 8000
