---
apiVersion: v1
kind: Service
metadata:
  name: gnomad-browser
  labels:
    app: gnomad-browser
    component: frontend
spec:
  type: NodePort
  selector:
    app: gnomad-browser
    component: frontend
    name: gnomad-browser
  ports:
    - port: 80
      targetPort: 8000
