---
apiVersion: v1
kind: Service
metadata:
  name: gnomad-browser-bluegreen
  labels:
    tier: production
  annotations:
    cloud.google.com/backend-config: '{{"ports": {{"80":"gnomad-backend-config"}}}}'
spec:
  type: NodePort
  selector:
    app: gnomad-browser
    deployment: blue
  ports:
    - port: 80
      targetPort: 80
