# For automatically updating the gnomad elasticsearch password in the GCP secret manager
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-espassword
spec:
  updatePolicy: Replace
  refreshInterval: 180s
  secretStoreRefs:
    - name: gcpsm
      kind: ClusterSecretStore
  selector:
    secret:
      name: gnomad-es-elastic-user # Source Kubernetes secret to be pushed
  data:
    - conversionStrategy: None
      match:
        secretKey: elastic # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: gnomad-v4-elasticsearch-password # Target GCP secret manager secret name
