---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rollout.yaml
  - active-service.yaml
  - preview-service.yaml
images:
  - name: gnomad-reads-server
    newName: us-docker.pkg.dev/gnomadev/gnomad/gnomad-reads-server
    newTag: 'dev-6cfd6ae0-reads_deployment'
  - name: gnomad-reads-api
    newName: us-docker.pkg.dev/gnomadev/gnomad/gnomad-reads-api
    newTag: 'dev-6cfd6ae0-reads_deployment'
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gnomad-reads
      spec:
        replicas: 0
        template:
          spec:
            volumes:
              - name: readviz
                gcePersistentDisk:
                  pdName: readviz-empty-test
