---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  # include this to allow for kustomize to apply suffixes to services in the rollout manifest
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
replicas:
  # scale the Deployment to 0 -- for prod replicas are managed by the rollout
  - name: gnomad-reads
    count: 0
resources:
  - ../base
  - rollout.yaml
  - active-service.yaml
  - preview-service.yaml
labels:
  - pairs:
      environment: prod
      component: reads
    includeSelectors: true
    includeTemplates: true
nameSuffix: -prod
images:
  - name: gnomad-reads-server
    newName: us-docker.pkg.dev/gnomadev/gnomad/gnomad-reads-server
    newTag: 'dev-6cfd6ae0-reads_deployment'
  - name: gnomad-reads-api
    newName: us-docker.pkg.dev/gnomadev/gnomad/gnomad-reads-api
    newTag: 'dev-6cfd6ae0-reads_deployment'
