apiVersion: v1
kind: Service
metadata:
  labels:
    app: gnomad-reads
  name: reads-bluegreen-preview
spec:
  selector:
    app: gnomad-reads
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
