apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
namePrefix: bipex2-demo-
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: qa
      name: bipex2-demo-exome-results-browsers
images:
  - name: exome-results-browsers
    newName: us-docker.pkg.dev/exac-gnomad/gnomad/exome-results-browsers
    newTag: 5742d84-bipex2-demo-2026-04-15--11-18
patches:
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: exome-results-browsers
      spec:
        template:
          spec:
            volumes:
              - name: data
                gcePersistentDisk:
                  pdName: erb-data-bipex2-demo-2026-04-15--09-22
